name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS
        run: |
          xcodebuild \
          -workspace ios/FISFIOS.xcworkspace \
          -scheme FISFIOS \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO